### ISSUE TITLE
Admin - Exam, Marks

### ISSUE THREAD

**Issue by sublimemahesh** [sublimemahesh/TuitionMaster#151]
Need to change the Manage Marks interface same as **Exam Page Type** in Admin 
If all in one page -> need to show all replies of the  question of the students in one page 
One by One -> Same as current design

Marks input max value must be less than or equal to the question marks.

Given question marks are not visible to the admin and student (Need to show marks of each question in admin and student interface near to the comment text )

**Comment by hansajith1998** [comment]
- Disable add new questions if any one of the student face the exam
